# Generated by Django 3.1 on 2020-08-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('books', models.ManyToManyField(blank=True, null=True, related_name='books', to='app.Book')),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
