# Generated by Django 3.1 on 2020-08-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_reserved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data reserva'),
        ),
    ]
